imports:
    - { resource: services/controller.yaml }
    - { resource: services/security.yml }
    - { resource: services/registration.yml }
    - { resource: services/reset_password.yml }
    - { resource: services/user_management.yaml }

parameters:
    vs_users.cookie_lifetime: 86400 # 24 hours
    vs_users.gc_maxlifetime: 1800   # 30 minutes
    vs_users.api_token.lifetime: 3600
    vs_users.api_token.domain: '%env(API_TOKEN_DOMAIN)%'

services:        
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

