parameters:
    vs_users.registration_form: 'Vankosoft\UsersBundle\Form\RegistrationFormType'
    vs_users.register_role: 'role-application-admin'

services:
    vs_users.registration_controller:
        public: true
        autowire: true
        class: Vankosoft\UsersBundle\Controller\RegisterController
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_users.manager.user'
            - '@vs_users.repository.users'
            - '@vs_users.factory.users'
            - '@vs_users.repository.user_roles'
            - '@mailer'
            - '@vs_cms.repository.pages'
            - {
                registrationForm: '%vs_users.registration_form%',
                registerRole: '%vs_users.register_role%',
                defaultRedirect: '%vs_users.default_redirect%',
                mailerUser: '%vs_application.mailer_user%',
            }
        calls:
            - setTokenGenerator: ['@?symfonycasts.verify_email.token_generator']
            - setVerifyEmailHelper: ['@?symfonycasts.verify_email.helper']

    vs_users.form.type.profile:
        class: Vankosoft\UsersBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: vs_users_profile }
        arguments:
            - "@request_stack"
            - '%vs_users.model.users.class%'
            - '%vs_application.model.application.class%'
            - '@security.helper'
            
    vs_users.form.type.registration:
        class: Vankosoft\UsersBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: vs_users_registration }
        arguments:
            - "@request_stack"
            - '%vs_users.model.users.class%'
            - '%vs_application.model.application.class%'
            - '@security.helper'
