parameters:
    vs_users.registration_form: 'Vankosoft\UsersBundle\Form\RegistrationFormType'
    vs_users.register_role: 'role-application-admin'
    vs_users.login_after_verify: true
    
    vs_users.registration_form_required_fields: []
    vs_users.profile_form_required_fields: []

services:
    vs_users.registration_controller:
        public: true
        autowire: true
        class: Vankosoft\UsersBundle\Controller\RegisterController
        tags: ['controller.service_arguments']
        arguments:
            - '@doctrine'
            - '@translator'
            - '@vs_application.context.application'
            - '@vs_users.manager.user'
            - '@vs_users.repository.users'
            - '@vs_users.factory.users'
            - '@vs_users.repository.user_roles'
            - '@mailer'
            - '@vs_cms.repository.pages'
            - '@security.user_authenticator'
            - '@vs_users.security.another_login_form_authenticator'
            - {
                registrationForm: '%vs_users.registration_form%',
                registerRole: '%vs_users.register_role%',
                defaultRedirect: '%vs_users.default_redirect%',
                mailerUser: '%vs_application.mailer_user%',
                loginAfterVerify: '%vs_users.login_after_verify%',
            }
        calls:
            - setContainer: [ '@service_container' ]
            - setTokenGenerator: ['@?symfonycasts.verify_email.token_generator']
            - setVerifyEmailHelper: ['@?symfonycasts.verify_email.helper']

    vs_users.form.type.profile:
        class: Vankosoft\UsersBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: vs_users_profile }
        arguments:
            - '%vs_users.model.users.class%'
            - '@vs_application.repository.locale'
            - '@request_stack'
            - '%vs_application.model.application.class%'
            - '@security.helper'
            - '%vs_users.profile_form_required_fields%'
            
    vs_users.form.type.registration:
        class: Vankosoft\UsersBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: vs_users_registration }
        arguments:
            - '%vs_users.model.users.class%'
            - '@vs_application.repository.locale'
            - '@request_stack'
            - '%vs_application.model.application.class%'
            - '@security.helper'
            - '%vs_users.registration_form_required_fields%'
