parameters:
    vs_users.login_route: 'vs_application_login'
    vs_users.login_by: 'email'
    vs_users.default_redirect: 'vs_application_dashboard'
    
    vs_users.form_create_account: true
    
    vs_users.gc_maxlifetime: 1800   # 30 minutes
    vs_users.cookie.domain: '%env(COOKIE_DOMAIN)%'
    vs_users.cookie.lifetime: 86400 # 24 hours
    vs_users.api_token.domain: '%env(API_TOKEN_DOMAIN)%'
    vs_users.api_token.lifetime: 3600 # 1 hours
    
    vs_users.voter.disabled_models: {}
#    Disabled Models Example
##########################################
#    vs_users.voter.disabled_models:
#        ROLE_TEST_APPLICATION_ADMIN:
#            'App\Entity\Post':
#                - 'edit'
#                - 'remove'
    
services:
    vs_users.manager.user:
        class: VS\UsersBundle\Security\UserManager
        public: true
        arguments:
            - '@vs_users.factory.users'
            - '@vs_users.repository.users'
            - '@doctrine.orm.entity_manager'
            - '@security.password_hasher_factory'
            - '@vs_users.factory.user_info'
    
    vs_users.security.login_form_authenticator:
        class: VS\UsersBundle\Security\LoginFormAuthenticator
        arguments:
            - '@router'
            - '@security.csrf.token_manager'
            - '@security.password_hasher_factory'
            - '@vs_users.repository.users'
            - {
                loginRoute: '%vs_users.login_route%',
                loginBy: '%vs_users.login_by%',
                defaultRedirect: '%vs_users.default_redirect%',
                apiTokenDomain: '%vs_users.api_token.domain%',
                apiTokenLifetime: '%vs_users.api_token.lifetime%'
            }

    vs_users.security.api_key_authenticator:
        class: VS\UsersBundle\Security\ApiKeyAuthenticator
        arguments:
            - '@vs_users.repository.users'

    # Register a listener for the logout event only on the main firewall
    # https://symfony.com/blog/new-in-symfony-5-1-simpler-logout-customization
    vs_users.security.logout_success_handler:
        class: VS\UsersBundle\Security\MainLogoutListener
        arguments:
            - '@security.http_utils'
            - '/'
        tags:
            - name: 'kernel.event_listener'
              event: 'Symfony\Component\Security\Http\Event\LogoutEvent'
              dispatcher: security.event_dispatcher.main

    vs_users.security.application_voter:
        class: VS\UsersBundle\Security\Voter\ApplicationVoter
        tags: ['security.voter']
        arguments:
            - '@security.context'
            - '@vs_application.context.application'
    
    vs_users.security.model_voter:
        class: VS\UsersBundle\Security\Voter\ModelVoter
        tags: ['security.voter']
        arguments:
            - '@security.context'
            - '@vs_application.context.application'
            - '%vs_users.voter.disabled_models%'
