ia_users_api_index:
    path:     /api/users
    defaults: { _controller: IAUsersBundle:Api:index }
    
ia_users_api_detail:
    path:     /api/users/detail/{id}
    defaults: { _controller: IAUsersBundle:Api:detail}

ia_users_api_delete:
    path:     /api/users/delete/{id}
    defaults: { _controller: IAUsersBundle:Api:delete }

ia_users_api_save:
    path:     /api/users/save
    defaults: { _controller: IAUsersBundle:Api:save }
    requirements:
        _method:  POST
