vs_users_crud_index_paginated:
    path: /users/
    methods: [GET]
    defaults:
        _controller: vs_users.controller.users:indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                id: asc
            filterable: true
            template: "@VSUsers/UsersCrud/index.html.twig"
    options:
        expose: true

vs_users_crud:
    resource: |
        alias: vs_users.users
        path: /users
        templates: "@VSUsers/UsersCrud"
    type: sylius.resource

vs_users_user_roles:
    resource: |
        alias: vs_users.user_roles
        path: /user-roles
        templates: "@VSUsers/UsersRoles"
    type: sylius.resource

vs_users_roles_tree_combo_with_selected:
    path: /json/{userId}/user-roles-collection/easyui-combotree
    controller: Vankosoft\UsersBundle\Controller\UsersExtController::rolesEasyuiComboTreeWithSelectedSource
    
vs_users_roles_collection_parent_tree_combo_with_selected:
    path: /json/{roleId}/user-roles-collection-parent/easyui-combotree
    controller: Vankosoft\UsersBundle\Controller\UsersRolesExtController::rolesEasyuiComboTreeWithSelectedSource
